//
//  FruitsAndBerriesModels.swift
//  iOS-Test
//

enum FruitsAndBerriesModels {
  // Models for "load (list)" use case
  struct Load {
    // Request is passed to Interactor
    struct Request {}
    // Response is passed from Interactor to Presenter
    struct Response {
      let title: String
      let items: [GroceryProduct]
    }
    
    // View model is generated by Presenter and passed to View
    struct ViewModel {
      let title: String
      let dataSource: [GroceryProductViewModel]
    }
    
  }
  
  struct Alert {
    
    struct Request {}
    
    struct Response {
      let title: String
      let message: String
    }
    
    struct ViewModel {
      let title: String
      let message: String
    }
    
  }
  
  struct Loading {
    
    struct Request {}
    
    struct Response {
      let isLoading: Bool
    }
    
    struct ViewModel {
      let isLoading: Bool
    }
    
  }
  
}
